###LG Volume Slider#### 
- alias: LG Volume Slider
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_slider.lg_volume_slider

  action:
    service: media_player.volume_set
    data_template:
      entity_id: media_player.living_room_tv
      volume_level: '{{ trigger.to_state.state }}'

- alias: Update LG Volume Slider
  hide_entity: true  
  trigger:
    platform: state
    entity_id: media_player.living_room_tv

  action:
    service: input_slider.select_value
    data_template:
      entity_id: input_slider.lg_volume_slider
      value: >
        {{ states.media_player.living_room_tv.attributes.volume_level }}

###Update Sonos Sliders#### 
- alias: Livingroom_sonos - Adjust Volume
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_slider.living_room

  action:
    service: media_player.volume_set
    data_template:
      entity_id: media_player.sonos_livingroom
      volume_level: '{{ trigger.to_state.state }}'

- alias: Bedroom_sonos - Adjust Volume
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_slider.bedroom

  action:
    service: media_player.volume_set
    data_template:
      entity_id: media_player.sonos_bedroom
      volume_level: '{{ trigger.to_state.state }}'

# second part of volume
- alias: Bedroom Group Volume Update
  hide_entity: true    
  trigger:
    platform: state
    entity_id: media_player.sonos_bedroom

  action:
    service: input_slider.select_value
    data_template:
      entity_id: input_slider.bedroom
      value: '{{ states.media_player.sonos_bedroom.attributes.volume_level }}'

- alias: Livingroom Group Volume Update
  hide_entity: true
  trigger:
    platform: state
    entity_id: media_player.sonos_livingroom

  action:
    service: input_slider.select_value
    data_template:
      entity_id: input_slider.living_room
      value: '{{ states.media_player.sonos_livingroom.attributes.volume_level }}'

###LG Source Select#### 
- alias: LG Source Select
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.lg_source

  action:
    service: media_player.select_source
    data_template:
      entity_id: media_player.living_room_tv
      source: '{{ trigger.to_state.state }}'

- alias: Update LG Source Select
  hide_entity: true
  trigger:
    platform: state
    entity_id: media_player.living_room_tv

  action:
    service: input_select.select_option
    data_template:
      entity_id: input_select.lg_source
      option: '{{ states.media_player.living_room_tv.attributes.source }}'

- alias: Update LG Source Select on startup
  hide_entity: true
  trigger:
    platform: event
    event_type: homeassistant_start

  action:
    service: input_select.select_option
    data_template:
      entity_id: input_select.lg_source
      option: '{{ states.media_player.living_room_tv.attributes.source }}'

- alias: Update LG Source Select when off
  hide_entity: true
  trigger:
    platform: state
    entity_id: media_player.living_room_tv
    from: 'playing'
    to: 'off'

  action:
    service: input_select.select_option
    data_template:
      entity_id: input_select.lg_source
      option: "Offline"

###Kodi Auto Start and Exit Bedroom#### 
- alias: Auto Start Kodi Bedroom
  hide_entity: true
  trigger:
    platform: time
    after: '6:50:00'

  action:
    service: shell_command.run_kodi_bedroom

- alias: Start Kodi Bedroom Monitor
  hide_entity: true
  trigger:
    platform: time
    after: '7:00:00'

  action:
    service: script.turn_on
    data_template:
      entity_id: script.kodi_autostart_bedroom

- alias: Auto Stop Kodi Bedroom
  hide_entity: true
  trigger:
    platform: time
    after: '2:00:00'

  action:
    service: script.turn_on
    data_template:
      entity_id: script.kodi_stop_bedroom

###Kodi Auto Start and Exit Livingroom#### 
- alias: Auto Start Kodi Livingroom
  hide_entity: true
  trigger:
    platform: time
    after: '19:00:00'

  action:
    service: script.turn_on
    data_template:
      entity_id: script.tv_power_on

- alias: Auto Stop Kodi Livingroom
  hide_entity: true
  trigger:
    platform: time
    after: '23:00:00'

  action:
    service: script.turn_on
    data_template:
      entity_id: script.tv_power_off

###Home Assistance Updated Notification#### 
- alias: Update notifications
  hide_entity: true
  trigger:
    platform: state
    entity_id: updater.updater

  action:
    service: notify.pushbullet
    data_template:
      title: "New Home Assistant Release"
      message: "Home Assistant  {{ states.updater.updater.state }}  is now available."

###Kodi Favorites Automation - Livingroom####
- alias: Kodi Channel 01 Livingroom
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.kodi_favorites_livingroom
    to: 'Channel 01 ABC'

  action:
    service: script.turn_on
    data_template:
      entity_id: script.kodi_channelpearfav1_livingroom

- alias: Kodi Channel 02 Livingroom
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.kodi_favorites_livingroom
    to: 'Channel 02 CBS'

  action:
    service: script.turn_on
    data_template:
      entity_id: script.kodi_channelpearfav2_livingroom

- alias: Kodi Channel 03 Livingroom
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.kodi_favorites_livingroom
    to: 'Channel 03 FOX'

  action:
    service: script.turn_on
    data_template:
      entity_id: script.kodi_channelpearfav3_livingroom

- alias: Kodi Channel 04 Livingroom
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.kodi_favorites_livingroom
    to: 'Channel 04 NBC'

  action:
    service: script.turn_on
    data_template:
      entity_id: script.kodi_channelpearfav4_livingroom

- alias: Kodi Channel 05 Livingroom
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.kodi_favorites_livingroom
    to: 'Channel 05 MSNBC'

  action:
    service: script.turn_on
    data_template:
      entity_id: script.kodi_channelpearfav5_livingroom

- alias: Kodi Channel 06 Livingroom
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.kodi_favorites_livingroom
    to: 'Channel 06 CNN'

  action:
    service: script.turn_on
    data_template:
      entity_id: script.kodi_channelpearfav6_livingroom

- alias: Kodi Channel 07 Livingroom
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.kodi_favorites_livingroom
    to: 'Channel 07 Music Choice R&B Soul'

  action:
    service: script.turn_on
    data_template:
      entity_id: script.kodi_channelpearfav7_livingroom

- alias: Kodi Channel 08 Livingroom
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.kodi_favorites_livingroom
    to: 'Channel 08 Music Choice Hip Hop R&B'

  action:
    service: script.turn_on
    data_template:
      entity_id: script.kodi_channelpearfav8_livingroom

- alias: Kodi Channel 09 Livingroom
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.kodi_favorites_livingroom
    to: 'Channel 09 HBO'

  action:
    service: script.turn_on
    data_template:
      entity_id: script.kodi_channelpearfav9_livingroom

- alias: Kodi Channel 10 Livingroom
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.kodi_favorites_livingroom
    to: 'Channel 10 Cinemax'

  action:
    service: script.turn_on
    data_template:
      entity_id: script.kodi_channelpearfav10_livingroom

- alias: Kodi Channel PsudoLiveTV Livingroom
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.kodi_favorites_livingroom
    to: 'Program 01 PsudoLiveTV'

  action:
    service: script.turn_on
    data_template:
      entity_id: script.kodi_psudolivetv_livingroom

- alias: Kodi Channel PsudoLiveTV Livingroom
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.kodi_favorites_livingroom
    to: 'Program 02 Super Favourites'

  action:
    service: script.turn_on
    data_template:
      entity_id: script.kodi_superfavourites_livingroom

- alias: Kodi Channel Google Music Livingroom
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.kodi_favorites_livingroom
    to: 'Program 03 Google Music'

  action:
    service: script.turn_on
    data_template:
      entity_id: script.kodi_googlemusic_livingroom

###Kodi Favorites Automation - Bedroom####
- alias: Kodi Channel 01 bedroom
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.kodi_favorites_bedroom
    to: 'Channel 01 ABC'

  action:
    service: script.turn_on
    data_template:
      entity_id: script.kodi_channelpearfav1_bedroom

- alias: Kodi Channel 02 bedroom
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.kodi_favorites_bedroom
    to: 'Channel 02 CBS'

  action:
    service: script.turn_on
    data_template:
      entity_id: script.kodi_channelpearfav2_bedroom

- alias: Kodi Channel 03 bedroom
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.kodi_favorites_bedroom
    to: 'Channel 03 FOX'

  action:
    service: script.turn_on
    data_template:
      entity_id: script.kodi_channelpearfav3_bedroom

- alias: Kodi Channel 04 bedroom
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.kodi_favorites_bedroom
    to: 'Channel 04 NBC'

  action:
    service: script.turn_on
    data_template:
      entity_id: script.kodi_channelpearfav4_bedroom

- alias: Kodi Channel 05 bedroom
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.kodi_favorites_bedroom
    to: 'Channel 05 MSNBC'

  action:
    service: script.turn_on
    data_template:
      entity_id: script.kodi_channelpearfav5_bedroom

- alias: Kodi Channel 06 bedroom
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.kodi_favorites_bedroom
    to: 'Channel 06 CNN'

  action:
    service: script.turn_on
    data_template:
      entity_id: script.kodi_channelpearfav6_bedroom

- alias: Kodi Channel 07 bedroom
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.kodi_favorites_bedroom
    to: 'Channel 07 Music Choice R&B Soul'

  action:
    service: script.turn_on
    data_template:
      entity_id: script.kodi_channelpearfav7_bedroom

- alias: Kodi Channel 08 bedroom
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.kodi_favorites_bedroom
    to: 'Channel 08 Music Choice Hip Hop R&B'

  action:
    service: script.turn_on
    data_template:
      entity_id: script.kodi_channelpearfav8_bedroom

- alias: Kodi Channel 09 bedroom
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.kodi_favorites_bedroom
    to: 'Channel 09 HBO'

  action:
    service: script.turn_on
    data_template:
      entity_id: script.kodi_channelpearfav9_bedroom

- alias: Kodi Channel 10 bedroom
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.kodi_favorites_bedroom
    to: 'Channel 10 Cinemax'

  action:
    service: script.turn_on
    data_template:
      entity_id: script.kodi_channelpearfav10_bedroom

- alias: Kodi Channel PsudoLiveTV bedroom
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.kodi_favorites_bedroom
    to: 'Program 01 PsudoLiveTV'

  action:
    service: script.turn_on
    data_template:
      entity_id: script.kodi_psudolivetv_bedroom

- alias: Kodi Channel PsudoLiveTV bedroom
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.kodi_favorites_bedroom
    to: 'Program 02 Super Favourites'

  action:
    service: script.turn_on
    data_template:
      entity_id: script.kodi_superfavourites_bedroom

- alias: Kodi Channel Google Music bedroom
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.kodi_favorites_bedroom
    to: 'Program 03 Google Music'

  action:
    service: script.turn_on
    data_template:
      entity_id: script.kodi_googlemusic_bedroom
